declare module "*mongoose";
declare module "*express";
declare module "*process";
declare module "*path";
declare module "*bcrypt";
declare module "*cors";
declare module "*morgan";
declare module "*jsonwebtoken";
declare module "*multer";
declare module "*cloudinary";
declare module "*flutterwave-node-v3";
declare module "*uuid";
declare module "*nodemailer";
declare module "*ejs";
declare module "*googleapis";
declare module "*slugify"
declare module "*bcryptjs";
